aco:
  ants: 20
  iterations: 50
  alpha: 1.0
  beta: 2.0
  evaporation: 0.1
  q: 100
  
network:
  default_speeds:
    motorway: 90
    trunk: 70
    primary: 50
    secondary: 40
    tertiary: 30
    residential: 25